### ISSUE TITLE
Images not displaying in push notification

### ISSUE THREAD

**Issue by neilmenon** [andreinwald/webpush-ios-example#1]
Hey,

Thanks for providing this example. I'm working on the new Web Push for iOS right now, it seems as if the image doesn't show in the notifications. I don't see it in your example notification either. I've tried various URLs, smaller images, etc. Have you figured out how to get the images to show?

Thanks!

**Comment by andreinwald** [comment]
Hello!

You can pass keys icon and image in push notification, as said in this standard https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification
In my example in frontend.js file:
```js
    const options = {
        body: "Additional text with some description",
        icon: "https://andreinwald.github.io/webpush-ios-example/images/favicon.png", 
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Orange_tabby_cat_sitting_on_fallen_leaves-Hisashi-01A.jpg/1920px-Orange_tabby_cat_sitting_on_fallen_leaves-Hisashi-01A.jpg",
        data: {
            "url": "https://andreinwald.github.io/webpush-ios-example/success.html",
            "message_id": "your_internal_unique_message_id_for_tracking"
        },
    };
```

Showing image (big one) depends on browser. Google Chrome on desktop - should show it.

Also remember that you should use https im image links

**Comment by neilmenon** [comment]
@andreinwald thanks for the reply and the example! To clarify, it seems no matter what I set for `icon` and `image` specifically for iOS web push notifications, they don't show. For `image` you mentioned depends on the browser, makes sense. But for `icon`, have you had any luck setting it to something different than the actual app icon? Perhaps they're not supported (yet)? After all, this is a pretty new thing for iOS!

**Comment by neilmenon** [comment]
@andreinwald found some insight after some digging,

https://www.pushengage.com/documentation/setting-up-web-push-notifications-for-ios-ipad/ says:

> 1. Icon – The icon specified in the manifest file. It can’t be changed for individual messages.

Hopefully they'll add support for rich text, images, and actions soon. Fingers crossed.
