### ISSUE TITLE
This sample web do not work in my server

### ISSUE THREAD

**Issue by marcoahp** [andreinwald/webpush-ios-example#2]
I've published this sample web in my server replacing the vapid key with my own one generated with your instructions, but when  I push the suscribe to notifications button, I get an error: 

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pushManager')
    at subscribeToPush (frontend.js:44:35)

What is the problem? (I use Microsoft IIS)

Problem Solved. I had to change the scope in register:
let swRegistration = await navigator.serviceWorker.register('https://********.**/serviceworker.js', {scope: '/'})	

This sample works fine in android devices. Is possible to make it works in chrome for desktop too?

**Comment by andreinwald** [comment]
Hello!
You can check in "chrome for desktop" original example https://andreinwald.github.io/webpush-ios-example
If it works - then answer in changes that you did or should do in your version of code.

**Comment by marcoahp** [comment]
Hello, Where could I find chrome for desktop original example?

**Comment by andreinwald** [comment]
https://andreinwald.github.io/webpush-ios-example

Works in my Chrome on MacOS

**Comment by marcoahp** [comment]
Ok, I thought that It worked in chrome for windows too. But not. Thanks

 

De: Andrii Reinvald ***@***.***> 
Enviado el: martes, 15 de octubre de 2024 14:34
Para: andreinwald/webpush-ios-example ***@***.***>
CC: marcoahp ***@***.***>; Author ***@***.***>
Asunto: Re: [andreinwald/webpush-ios-example] This sample web do not work in my server (Issue #2)

 

https://andreinwald.github.io/webpush-ios-example

Works in my Chrome on MacOS
